services:
  web:
    container_name: web
    build:
      context: web
    tty: true
    depends_on:
      - db
    volumes:
      - ./web:/app
      - /app/node_modules
    restart: always

  db:
    image: mysql:8.1
    container_name: db
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - web
      - db